# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Compute the densities of given vector
#'
#' @description
#' C++ function to compute the density or distibution at each point of a
#' given vector. The supported distributions are \code{gaussian},
#' \code{logistic} and (least) \code{extreme value}.
#' \emph{This is used for testing, and may not be useful otherwise.}
#'
#' @param z Vector of points at which the densities are to be calculated.
#'
#' @param j If \code{1}, the returned vector contains
#' 0, f, f'/f and f''/f, where, f is the
#' density function of the given distribution.
#' If 2, returned vector contains F, 1-F, f and f', where F is the
#' distribution function.
#'
#' @param family The distribution of the data. \code{Guassian}, \code{logistic} and
#' (least) \code{extreme value} distributions are supported.
compute_densities <- function(z, j, family) {
    .Call('iregnet_compute_densities', PACKAGE = 'iregnet', z, j, family)
}

#' @title Compute the gradients of the log Likelihood wrt beta, and scale
#'
#' @description
#' C++ function to compute the gradients of log likelihood with respect to the
#' coefficients \code{beta} and \code{scale}.
#' The supported distributions are \code{gaussian},
#' \code{logistic} and (least) \code{extreme value}.
#' \emph{This is used for testing, and may not be useful otherwise.}
#'
#' @param X Design matrix.
#' @param y Output matrix in 2 column format.
#' @param eta Linear predictors.
#' @param scale Scale.
#' @param family The distribution of the data. \code{Guassian}, \code{logistic} and
#' (least) \code{extreme value} distributions are supported.
iregnet_compute_gradients <- function(X, y, eta, scale, family) {
    .Call('iregnet_iregnet_compute_gradients', PACKAGE = 'iregnet', X, y, eta, scale, family)
}

#' @title C++ function to fit interval censored models with elastic net
#'   penalty.
#'
#' @description \strong{This function is not meant to be called
#' on it's own!} Please use the \code{\link{iregnet}} function which includes
#' data validation and pre-processing.
#'
#' @param X Design matrix.
#' @param y Output matrix in a 2 column format. \code{NA}s denote censoring.
#' @param family String denoting the distribution to be fit.
#' @param lambda_path Vector containing the path of hyper-parameter lambda
#'   values.
#' @param debug Integer used for debugging during development. Unused otherwise.
#' @param out_status Vector containing censoring status of each observation.
#'   If not provided, it will be calculated using the \code{y} matrix.
#' @param intercept If \code{true}, intercept is to be fit. The first column
#'   of X must be \code{1}s if \code{intercept} is \code{true}.
#' @param alpha Hyper parameter for the elastic-net penalty.
#' @param scale_init The initial value of \code{scale} to be used for the fit.
#'   If not provided, a value is calculated depending on the distribution.
#' @param estimate_scale If \code{true}, \code{scale} is estimated. Else, the
#'     \code{scale} remains fixed at \code{scale_init}.
#' @param max_iter Maximum number of iterations to allow for \strong{each}
#'     model (\code{lambda} value) along the regularization path.
#' @param unreg_sol If \code{true}, the last model fit will be unregularized,
#'    i.e., the final \code{lambda} value will be \code{0}. Only used if
#'    \code{lambda_path} is not specified.
#' @param flag_standardize_x If \code{true}, the design matrix \code{X} will
#'     column-wise standardized.
#' @param threshold Convergence detected if absolute change in a coefficient
#'     is less than this value.
#' @param num_lambda Number of lambda values to use in the regularization
#'    path. Only used if \code{lambda_path} is not specified.
#' @param eps_lambda Ratio between the maximum and minimum values of
#'     \code{lambda}. Maximum value of \code{lambda} is calculated based on
#'     the distribution and the data. Only used if \code{lambda_path} is not
#'     specified.
#'
fit_cpp <- function(X, y, family, lambda_path, debug, out_status, intercept, alpha, scale_init, estimate_scale, unreg_sol, flag_standardize_x, max_iter, threshold, num_lambda, eps_lambda) {
    .Call('iregnet_fit_cpp', PACKAGE = 'iregnet', X, y, family, lambda_path, debug, out_status, intercept, alpha, scale_init, estimate_scale, unreg_sol, flag_standardize_x, max_iter, threshold, num_lambda, eps_lambda)
}

