# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_densities <- function(z, j, family) {
    .Call('iregnet_compute_densities', PACKAGE = 'iregnet', z, j, family)
}

iregnet_compute_gradients <- function(X, y, eta, scale, family) {
    .Call('iregnet_iregnet_compute_gradients', PACKAGE = 'iregnet', X, y, eta, scale, family)
}

#' @title C++ function to fit regularized AFT models with interval censored data
#' @description \strong{NOTE:} This function is not meant to be called on it's own! Please use
#' the \code{\link{iregnet}} function.
fit_cpp <- function(X, y, family, lambda_path, debug, out_status, intercept, alpha, scale_init, estimate_scale, unreg_sol, flag_standardize_x, max_iter, threshold, num_lambda, eps_lambda) {
    .Call('iregnet_fit_cpp', PACKAGE = 'iregnet', X, y, family, lambda_path, debug, out_status, intercept, alpha, scale_init, estimate_scale, unreg_sol, flag_standardize_x, max_iter, threshold, num_lambda, eps_lambda)
}

